CREATE TABLE FK_TABLE (
  FK_TABLE_ID NUMBER(18) NOT NULL ,
  TEST_NAME VARCHAR2(30 CHAR)
);
COMMENT ON table FK_TABLE is '外部テーブル';
COMMENT ON column FK_TABLE.FK_TABLE_ID is 'FK_TABLE_ID';
COMMENT ON column FK_TABLE.TEST_NAME is 'TEST_NAME';
CREATE SEQUENCE FK_TABLE_ID_SEQ increment by 1 start with 1;

