CREATE TABLE N_AUTO5 (
  N_AUTO5_ID NUMBER(18) NOT NULL ,
  SUB_ID NUMBER(18) NOT NULL ,
  TEST_NAME VARCHAR2(30 CHAR)
);
COMMENT ON table N_AUTO5 is 'NOT自動採番５';
COMMENT ON column N_AUTO5.N_AUTO5_ID is 'N_AUTO5_ID';
COMMENT ON column N_AUTO5.SUB_ID is 'SUB_ID';
COMMENT ON column N_AUTO5.TEST_NAME is 'TEST_NAME';



