CREATE TABLE PUBLIC.TYPETEST (
  TYPE1 BIGINT,
  TYPE2 BINARY,
  TYPE3 BLOB,
  TYPE4 CHAR,
  TYPE5 CLOB,
  TYPE6 DATE,
  TYPE7 DECIMAL,
  TYPE8 IDENTITY,
  TYPE9 INT,
  TYPE10 OTHER,
  TYPE11 REAL,
  TYPE12 SMALLINT,
  TYPE13 TIME,
  TYPE14 TIMESTAMP,
  TYPE15 VARCHAR,
  TYPE16 VARCHAR_IGNORECASE
);
COMMENT ON table PUBLIC.TYPETEST is 'タイプテスト';
COMMENT ON column PUBLIC.TYPETEST.TYPE1 is 'TYPE1';
COMMENT ON column PUBLIC.TYPETEST.TYPE2 is 'TYPE2';
COMMENT ON column PUBLIC.TYPETEST.TYPE3 is 'TYPE3';
COMMENT ON column PUBLIC.TYPETEST.TYPE4 is 'TYPE4';
COMMENT ON column PUBLIC.TYPETEST.TYPE5 is 'TYPE5';
COMMENT ON column PUBLIC.TYPETEST.TYPE6 is 'TYPE6';
COMMENT ON column PUBLIC.TYPETEST.TYPE7 is 'TYPE7';
COMMENT ON column PUBLIC.TYPETEST.TYPE8 is 'TYPE8';
COMMENT ON column PUBLIC.TYPETEST.TYPE9 is 'TYPE9';
COMMENT ON column PUBLIC.TYPETEST.TYPE10 is 'TYPE10';
COMMENT ON column PUBLIC.TYPETEST.TYPE11 is 'TYPE11';
COMMENT ON column PUBLIC.TYPETEST.TYPE12 is 'TYPE12';
COMMENT ON column PUBLIC.TYPETEST.TYPE13 is 'TYPE13';
COMMENT ON column PUBLIC.TYPETEST.TYPE14 is 'TYPE14';
COMMENT ON column PUBLIC.TYPETEST.TYPE15 is 'TYPE15';
COMMENT ON column PUBLIC.TYPETEST.TYPE16 is 'TYPE16';
