CREATE TABLE TEST_TBL3 (
  TEST_TBL3_ID BIGINT NOT NULL  COMMENT 'TEST_TBL3_ID',
  SEQTEST_AUTO BIGINT NULL DEFAULT NULL  COMMENT 'SEQTEST_AUTO',
  SEQTEST_ID BIGINT NULL DEFAULT NULL  COMMENT 'SEQTEST_ID'
)
COMMENT='テストテーブル3'