CREATE TABLE SCHEMA_TEST.TEST_TBL1_TEST (
  TEST_TBL1_ID BIGINT NOT NULL ,
  TEST_NAME VARCHAR(30)
);
COMMENT ON table TEST_TBL1 is 'テストテーブル1';
COMMENT ON column SCHEMA_TEST.TEST_TBL1.TEST_TBL1_ID is 'TEST_TBL1_ID';
COMMENT ON column SCHEMA_TEST.TEST_TBL1.TEST_NAME is 'TEST_NAME';
CREATE SEQUENCE TEST_TBL1_ID_SEQ increment by 1 start with 1;
