CREATE TABLE PUBLIC.TEST_TBL3 (
  TEST_TBL3_ID IDENTITY NOT NULL,
  SEQTEST_AUTO BIGINT,
  SEQTEST_ID BIGINT,
  PRIMARY KEY (TEST_TBL3_ID)
);
COMMENT ON table PUBLIC.TEST_TBL3 is 'テストテーブル3';
COMMENT ON column PUBLIC.TEST_TBL3.TEST_TBL3_ID is 'TEST_TBL3_ID';
COMMENT ON column PUBLIC.TEST_TBL3.SEQTEST_AUTO is 'SEQTEST_AUTO';
COMMENT ON column PUBLIC.TEST_TBL3.SEQTEST_ID is 'SEQTEST_ID';
