CREATE TABLE A_TABLE (
  A_ID NUMBER NOT NULL ,
  B_ID NUMBER,
  C_ID NUMBER,
  TEST_NAME VARCHAR2(100 CHAR),
  TEST1 VARCHAR2(100 CHAR),
  TEST2 VARCHAR2(500 CHAR),
  TEST3 VARCHAR2(500 CHAR)
);
COMMENT ON table A_TABLE is 'A_TABLE';
COMMENT ON column A_TABLE.A_ID is 'A_ID';
COMMENT ON column A_TABLE.B_ID is 'B_ID';
COMMENT ON column A_TABLE.C_ID is 'C_ID';
COMMENT ON column A_TABLE.TEST_NAME is 'TEST_NAME';
COMMENT ON column A_TABLE.TEST1 is 'TEST1';
COMMENT ON column A_TABLE.TEST2 is 'TEST2';
COMMENT ON column A_TABLE.TEST3 is 'TEST3';
CREATE SEQUENCE A_ID_SEQ increment by 1 start with 1;
