CREATE TABLE TYPETEST (
  TYPE2 CHAR(10 CHAR),
  TYPE4 DATE,
  TYPE5 LONG,
  TYPE6 NCHAR(10),
  TYPE8 NUMBER(10,2),
  TYPE9 NVARCHAR2(10),
  TYPE10 TIMESTAMP,
  TYPE11 VARCHAR2(10 CHAR),
  TYPE12 FLOAT(8)
);
COMMENT ON table TYPETEST is 'タイプテスト';
COMMENT ON column TYPETEST.TYPE2 is 'TYPE2';
COMMENT ON column TYPETEST.TYPE4 is 'TYPE4';
COMMENT ON column TYPETEST.TYPE5 is 'TYPE5';
COMMENT ON column TYPETEST.TYPE6 is 'TYPE6';
COMMENT ON column TYPETEST.TYPE8 is 'TYPE8';
COMMENT ON column TYPETEST.TYPE9 is 'TYPE9';
COMMENT ON column TYPETEST.TYPE10 is 'TYPE10';
COMMENT ON column TYPETEST.TYPE11 is 'TYPE11';
COMMENT ON column TYPETEST.TYPE12 is 'TYPE12';