CREATE TABLE PUBLIC.SEQUENCE_TEST (
  SEQUENCE_TEST_ID BIGINT NOT NULL,
  SUB_ID_1 BIGINT NOT NULL,
  SUB_ID_2 BIGINT NOT NULL,
  PRIMARY KEY (SEQUENCE_TEST_ID)
);
COMMENT ON table PUBLIC.SEQUENCE_TEST is 'SEQUENCE_TEST';
COMMENT ON column PUBLIC.SEQUENCE_TEST.SEQUENCE_TEST_ID is 'SEQUENCE_TEST_ID';
COMMENT ON column PUBLIC.SEQUENCE_TEST.SUB_ID_1 is 'SUB_ID_1';
COMMENT ON column PUBLIC.SEQUENCE_TEST.SUB_ID_2 is 'SUB_ID_2';
