CREATE TABLE SCHEMA_TEST.TEST_TBL2 (
  TEST_TBL2_ID BIGINT NOT NULL  COMMENT 'TEST_TBL2_ID',
  TEST_TBL1_ID BIGINT NOT NULL  COMMENT 'TEST_TBL1_ID',
  TEST_NAME VARCHAR(20) NULL DEFAULT NULL  COMMENT 'TEST_NAME'
)
COMMENT='テストテーブル2'