CREATE TABLE SCHEMA_TEST.INDEX_TEST2 (
  INDEX_TEST2_ID BIGINT NOT NULL  COMMENT 'INDEX_TEST2_ID',
  SUB_ID_1 BIGINT NOT NULL  COMMENT 'SUB_ID_1',
  SUB_ID_2 BIGINT NOT NULL  COMMENT 'SUB_ID_2'
)
COMMENT='INDEX_TEST2'