CREATE TABLE TYPETEST (
  TYPE1 BLOB,
  TYPE2 CHAR(10 CHAR),
  TYPE3 CLOB,
  TYPE4 DATE,
  TYPE5 LONG,
  TYPE6 NCHAR(10),
  TYPE7 NCLOB,
  TYPE8 NUMBER(10,2),
  TYPE9 NVARCHAR2(10),
  TYPE10 TIMESTAMP,
  TYPE11 VARCHAR2(10 CHAR)
);
COMMENT ON table TYPETEST is 'タイプテスト';
COMMENT ON column TYPETEST.TYPE1 is 'TYPE1';
COMMENT ON column TYPETEST.TYPE2 is 'TYPE2';
COMMENT ON column TYPETEST.TYPE3 is 'TYPE3';
COMMENT ON column TYPETEST.TYPE4 is 'TYPE4';
COMMENT ON column TYPETEST.TYPE5 is 'TYPE5';
COMMENT ON column TYPETEST.TYPE6 is 'TYPE6';
COMMENT ON column TYPETEST.TYPE7 is 'TYPE7';
COMMENT ON column TYPETEST.TYPE8 is 'TYPE8';
COMMENT ON column TYPETEST.TYPE9 is 'TYPE9';
COMMENT ON column TYPETEST.TYPE10 is 'TYPE10';
COMMENT ON column TYPETEST.TYPE11 is 'TYPE11';
