CREATE TABLE INDEX_TEST3 (
  INDEX_TEST3_ID BIGINT NOT NULL  COMMENT 'INDEX_TEST3_ID',
  SUB_ID_1 BIGINT NOT NULL  COMMENT 'SUB_ID_1',
  SUB_ID_2 BIGINT NOT NULL  COMMENT 'SUB_ID_2'
)
COMMENT='INDEX_TEST3'