CREATE TABLE public.TEST_TBL1 (
  TEST_TBL1_ID SERIAL NOT NULL,
  TEST_NAME VARCHAR(30),
  PRIMARY KEY (TEST_TBL1_ID)
);
COMMENT ON table public.TEST_TBL1 is 'テストテーブル1';
COMMENT ON column public.TEST_TBL1.TEST_TBL1_ID is 'TEST_TBL1_ID';
COMMENT ON column public.TEST_TBL1.TEST_NAME is 'TEST_NAME';
