CREATE TABLE public.TEST_TBL2 (
  TEST_TBL2_ID BIGINT NOT NULL,
  TEST_TBL1_ID SERIAL NOT NULL,
  TEST_NAME VARCHAR(20),
  PRIMARY KEY (TEST_TBL2_ID, TEST_TBL1_ID)
);
COMMENT ON table public.TEST_TBL2 is 'テストテーブル2';
COMMENT ON column public.TEST_TBL2.TEST_TBL2_ID is 'TEST_TBL2_ID';
COMMENT ON column public.TEST_TBL2.TEST_TBL1_ID is 'TEST_TBL1_ID';
COMMENT ON column public.TEST_TBL2.TEST_NAME is 'TEST_NAME';
