CREATE TABLE N_AUTO5 (
  N_AUTO5_ID BIGINT NOT NULL  COMMENT 'N_AUTO5_ID',
  SUB_ID BIGINT NOT NULL  COMMENT 'SUB_ID',
  TEST_NAME VARCHAR(30) NULL DEFAULT NULL  COMMENT 'TEST_NAME'
)
COMMENT='NOT自動採番５'