-- シーケンス
-- MySQLはシーケンスなし

-- シノニム
-- MySQLにはシノニムなし

-- プロシージャ
CREATE PROCEDURE PROC_SELECT_TEST_TBL1(IN AA INT, OUT BB INT) BEGIN SELECT TEST_TBL1_ID INTO BB FROM TEST_TBL1 WHERE TEST_TBL1_ID = AA; END;

-- ファンクション
CREATE FUNCTION set_plus2() RETURNS INT DETERMINISTIC BEGIN RETURN (f + 2); END;

-- トリガ
CREATE TRIGGER trigger_update_aa AFTER INSERT ON TEST_TBL2 FOR EACH ROW BEGIN UPDATE TEST_TBL1 SET TEST_NAME = CONCAT(TEST_NAME, 'aa') WHERE TEST_TBL1_ID = NEW.TEST_TBL1_ID; END;