CREATE TABLE D_TABLE (
  D_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  TEST_NAME VARCHAR(100),
  TEST1 VARCHAR(100),
  TEST2 VARCHAR(500),
  TEST3 VARCHAR(500)
);
COMMENT ON table D_TABLE is 'D_TABLE';
COMMENT ON column D_TABLE.D_ID is 'D_ID';
COMMENT ON column D_TABLE.TEST_NAME is 'TEST_NAME';
COMMENT ON column D_TABLE.TEST1 is 'TEST1';
COMMENT ON column D_TABLE.TEST2 is 'TEST2';
COMMENT ON column D_TABLE.TEST3 is 'TEST3';
