CREATE TABLE AUTO1 (
  AUTO1_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  TEST_NAME VARCHAR(30)
);
COMMENT ON table AUTO1 is '自動採番１';
COMMENT ON column AUTO1.AUTO1_ID is 'AUTO1_ID';
COMMENT ON column AUTO1.TEST_NAME is 'TEST_NAME';
