CREATE TABLE N_AUTO5 (
  N_AUTO5_ID BIGINT NOT NULL,
  SUB_ID BIGINT NOT NULL,
  TEST_NAME VARCHAR(30)
);
COMMENT ON table N_AUTO5 is 'NOT自動採番５';
COMMENT ON column N_AUTO5.N_AUTO5_ID is 'N_AUTO5_ID';
COMMENT ON column N_AUTO5.SUB_ID is 'SUB_ID';
COMMENT ON column N_AUTO5.TEST_NAME is 'TEST_NAME';
