CREATE TABLE N_AUTO3 (
  N_AUTO3_ID VARCHAR(10) NOT NULL,
  TEST_NAME VARCHAR(30)
);
COMMENT ON table N_AUTO3 is 'NOT自動採番３';
COMMENT ON column N_AUTO3.N_AUTO3_ID is 'N_AUTO3_ID';
COMMENT ON column N_AUTO3.TEST_NAME is 'TEST_NAME';
