CREATE TABLE GSPANOTHER.C_TABLE (
  C_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  TEST_NAME VARCHAR(100),
  TEST1 VARCHAR(100),
  TEST2 VARCHAR(500),
  TEST3 VARCHAR(500)
);
COMMENT ON table GSPANOTHER.C_TABLE is 'C_TABLE';
COMMENT ON column GSPANOTHER.C_TABLE.C_ID is 'C_ID';
COMMENT ON column GSPANOTHER.C_TABLE.TEST_NAME is 'TEST_NAME';
COMMENT ON column GSPANOTHER.C_TABLE.TEST1 is 'TEST1';
COMMENT ON column GSPANOTHER.C_TABLE.TEST2 is 'TEST2';
COMMENT ON column GSPANOTHER.C_TABLE.TEST3 is 'TEST3';
