CREATE TABLE SCHEMA_TEST.TEST_TBL3_TEST (
  TEST_TBL3_ID BIGSERIAL NOT NULL ,
  SEQTEST_AUTO SERIAL,
  SEQTEST_ID BIGINT
);
COMMENT ON table TEST_TBL3 is 'テストテーブル3';
COMMENT ON column SCHEMA_TEST.TEST_TBL3.TEST_TBL3_ID is 'TEST_TBL3_ID';
COMMENT ON column SCHEMA_TEST.TEST_TBL3.SEQTEST_AUTO is 'SEQTEST_AUTO';
COMMENT ON column SCHEMA_TEST.TEST_TBL3.SEQTEST_ID is 'SEQTEST_ID';
