CREATE TABLE TEST_TBL3 (
  TEST_TBL3_ID NUMBER NOT NULL ,
  TEST_TBL1_ID NUMBER NOT NULL ,
  TEST_NAME VARCHAR2(20 CHAR)
);
COMMENT ON table TEST_TBL3 is 'テストテーブル3';
COMMENT ON column TEST_TBL3.TEST_TBL3_ID is 'TEST_TBL3_ID';
COMMENT ON column TEST_TBL3.TEST_TBL1_ID is 'TEST_TBL1_ID';
COMMENT ON column TEST_TBL3.TEST_NAME is 'TEST_NAME';



