CREATE TABLE TEST_TBL4 (
  TEST_TBL4_ID NUMBER NOT NULL ,
  SUB_ID NUMBER NOT NULL ,
  TEST_NAME VARCHAR2(30 CHAR),
  TEST_ID NUMBER NOT NULL 
);
COMMENT ON table TEST_TBL4 is 'テストテーブル4';
COMMENT ON column TEST_TBL4.TEST_TBL4_ID is 'TEST_TBL4_ID';
COMMENT ON column TEST_TBL4.SUB_ID is 'SUB_ID';
COMMENT ON column TEST_TBL4.TEST_NAME is 'TEST_NAME';
COMMENT ON column TEST_TBL4.TEST_ID is 'TEST_ID';




