CREATE TABLE PUBLIC.TEST_TBL2 (
  TEST_TBL2_ID BIGINT NOT NULL,
  TEST_TBL1_ID IDENTITY NOT NULL,
  TEST_NAME VARCHAR(20),
  PRIMARY KEY (TEST_TBL1_ID)
);
COMMENT ON table PUBLIC.TEST_TBL2 is 'テストテーブル2';
COMMENT ON column PUBLIC.TEST_TBL2.TEST_TBL2_ID is 'TEST_TBL2_ID';
COMMENT ON column PUBLIC.TEST_TBL2.TEST_TBL1_ID is 'TEST_TBL1_ID';
COMMENT ON column PUBLIC.TEST_TBL2.TEST_NAME is 'TEST_NAME';
