CREATE TABLE C_TABLE (
  C_ID NUMBER NOT NULL ,
  TEST_NAME VARCHAR2(100 CHAR),
  TEST1 VARCHAR2(100 CHAR),
  TEST2 VARCHAR2(500 CHAR),
  TEST3 VARCHAR2(500 CHAR)
);
COMMENT ON table C_TABLE is 'C_TABLE';
COMMENT ON column C_TABLE.C_ID is 'C_ID';
COMMENT ON column C_TABLE.TEST_NAME is 'TEST_NAME';
COMMENT ON column C_TABLE.TEST1 is 'TEST1';
COMMENT ON column C_TABLE.TEST2 is 'TEST2';
COMMENT ON column C_TABLE.TEST3 is 'TEST3';
CREATE SEQUENCE C_ID_SEQ increment by 1 start with 1;




