CREATE TABLE N_AUTO3 (
  N_AUTO3_ID VARCHAR2(10 CHAR) NOT NULL ,
  TEST_NAME VARCHAR2(30 CHAR)
);
COMMENT ON table N_AUTO3 is 'NOT自動採番３';
COMMENT ON column N_AUTO3.N_AUTO3_ID is 'N_AUTO3_ID';
COMMENT ON column N_AUTO3.TEST_NAME is 'TEST_NAME';


