CREATE TABLE N_AUTO4 (
  N_AUTO4_ID NUMBER(18) NOT NULL ,
  TEST_NAME VARCHAR2(30 CHAR)
);
COMMENT ON table N_AUTO4 is 'NOT自動採番４';
COMMENT ON column N_AUTO4.N_AUTO4_ID is 'N_AUTO4_ID';
COMMENT ON column N_AUTO4.TEST_NAME is 'TEST_NAME';


