CREATE TABLE N_AUTO6 (
  FK_TABLE_ID NUMBER(18) NOT NULL ,
  TEST_NAME VARCHAR2(30 CHAR)
);
COMMENT ON table N_AUTO6 is 'NOT自動採番６';
COMMENT ON column N_AUTO6.FK_TABLE_ID is 'FK_TABLE_ID';
COMMENT ON column N_AUTO6.TEST_NAME is 'TEST_NAME';


