CREATE TABLE SCHEMA_TEST.TEST_TBL1 (
  TEST_TBL1_ID NUMBER NOT NULL ,
  TEST_NAME VARCHAR2(30 CHAR)
);
COMMENT ON table SCHEMA_TEST.TEST_TBL1 is 'テストテーブル1';
COMMENT ON column SCHEMA_TEST.TEST_TBL1.TEST_TBL1_ID is 'TEST_TBL1_ID';
COMMENT ON column SCHEMA_TEST.TEST_TBL1.TEST_NAME is 'TEST_NAME';
CREATE SEQUENCE SCHEMA_TEST.TEST_TBL1_ID_SEQ increment by 1 start with 1;

